---
- name: Install k3s server service
  get_url: 
    url: https://raw.githubusercontent.com/rancher/k3s/master/k3s.service
    dest: /etc/systemd/system/k3s-server.service
    mode: a+x
    force: yes

- name: Ensure environment file exists
  copy:
    content: ""
    dest: /etc/systemd/system/k3s.service.env
    force: no
    group: sys
    owner: root
    mode: 0644

- name: Enable and start the k3s server service
  service:
    name: k3s-server
    enabled: yes
    state: started
