---
- name: Ensure US locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set hostname to inventory hostname
  hostname: name={{inventory_hostname}}

- name: Update apt cache and upgrade
  apt:
    update_cache: yes
    upgrade: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Get iptables version
  shell:
    cmd: iptables --version | grep -o '[0-9.]*'
  register: iptables_version

- name: Ensure that legacy iptables are used (iptables 1.8.0+)
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy
  when: iptables_version.stdout is version('1.8.0', '>=')
