---
- name: Ensure US locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set hostname to inventory hostname
  hostname: name={{inventory_hostname}}

- name: Update apt cache and upgrade
  apt:
    update_cache: yes
    upgrade: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Get iptables version
  shell:
    cmd: iptables --version | grep -o '[0-9.]*'
  register: iptables_version

- name: Ensure that legacy iptables are used (iptables 1.8.0+)
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy
  when: iptables_version.stdout is version('1.8.0', '>=')

- name: Get IP Address
  shell:
    cmd: hostname -i
  register: ipaddress

- name: Generate short hostname
  set_fact:
    inventory_shortname: "{{ ansible_nodename.split('.')[0] }}"

- name: Generate /etc/hosts file
  become: true
  blockinfile:
    path: /etc/hosts
    create: yes
    block: |
      127.0.0.1 localhost

      # The following lines are desirable for IPv6 capable hosts
      ::1 ip6-localhost ip6-loopback
      fe00::0 ip6-localnet
      ff00::0 ip6-mcastprefix
      ff02::1 ip6-allnodes
      ff02::2 ip6-allrouters
      ff02::3 ip6-allhosts

      {{ipaddress.stdout}}   {{inventory_hostname}}   {{inventory_shortname}}

